version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./dist:/var/www/niceandneat.dev
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./certbot/keys:/etc/nginx/keys
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/_letsencrypt
    ports:
      - 80:80
      - 443:443
    entrypoint: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/keys:/etc/keys
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/_letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
